### ISSUE TITLE
直播间开播后Mirai报错，消息没有发出到群

### ISSUE THREAD

**Issue by Soarniner** [Lycreal/MiraiBot#19]
我加入了我自己的B站直播间测试，开播后机器人后台看有反应，但是报错了
Bot这边
[2021-04-09 02:11:40][Mirai] INFO: Event: ZHAviation直播：https://live.bilibili.com/4113050
[2021-04-09 02:11:42][Mirai] INFO: Protocol: protocol method uploadImage was called
[2021-04-09 02:11:43][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2021-04-09 02:11:48][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2021-04-09 02:11:53][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2021-04-09 02:11:58][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2021-04-09 02:12:03][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2021-04-09 02:12:08][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2021-04-09 02:12:13][Mirai] ERROR: Protocol: we retried many times, but it doesn't send a success message to us...
[2021-04-09 02:12:13][Mirai] INFO: Protocol: protocol method sendGroupMessage was called

Mirai这边
2021-04-09 10:11:43 E/net.mamoe.mirai-api-http: java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
        at net.mamoe.mirai.internal.MiraiImpl.createImage(MiraiImpl.kt:901)
        at net.mamoe.mirai.message.data.Image$Key.fromId(Image.kt:123)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:276)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:172)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:327)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-09 10:11:48 E/net.mamoe.mirai-api-http: java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
        at net.mamoe.mirai.internal.MiraiImpl.createImage(MiraiImpl.kt:901)
        at net.mamoe.mirai.message.data.Image$Key.fromId(Image.kt:123)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:276)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:172)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:327)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-09 10:11:53 E/net.mamoe.mirai-api-http: java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
        at net.mamoe.mirai.internal.MiraiImpl.createImage(MiraiImpl.kt:901)
        at net.mamoe.mirai.message.data.Image$Key.fromId(Image.kt:123)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:276)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:172)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:327)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-09 10:11:58 E/net.mamoe.mirai-api-http: java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
        at net.mamoe.mirai.internal.MiraiImpl.createImage(MiraiImpl.kt:901)
        at net.mamoe.mirai.message.data.Image$Key.fromId(Image.kt:123)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:276)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:172)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:327)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-09 10:12:03 E/net.mamoe.mirai-api-http: java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
        at net.mamoe.mirai.internal.MiraiImpl.createImage(MiraiImpl.kt:901)
        at net.mamoe.mirai.message.data.Image$Key.fromId(Image.kt:123)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:276)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:172)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:327)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-09 10:12:08 E/net.mamoe.mirai-api-http: java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
java.lang.IllegalArgumentException: Illegal imageId: {{10DAB641-BF3F-C910-6183-E946F453C5B7}.jpg}.mirai. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
        at net.mamoe.mirai.internal.MiraiImpl.createImage(MiraiImpl.kt:901)
        at net.mamoe.mirai.message.data.Image$Key.fromId(Image.kt:123)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:276)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:172)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:327)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Lycreal** [comment]
估计是 `mirai-api-http` 的图片接口变动了。`python-mirai` 原作者停止维护了，适配的是老版本的 `mirai-api-http`。

安装 [这个](https://github.com/Lycreal/python-mirai/tree/fix-GroupImage) 应该能修复：
```shell
pip install https://github.com/Lycreal/python-mirai/archive/refs/heads/fix-GroupImage.zip
```

[d22b14b](https://github.com/Lycreal/python-mirai/commit/d22b14b5c2b2ee8500e1fc5d365035fdb970c7ab)

**Comment by Soarniner** [comment]
装了这个之后还是一模一样的报错喔
安装：
[root@vm103922 MiraiBot]# pip3 install https://github.com/Lycreal/python-mirai/archive/refs/heads/fix-GroupImage.zip
Collecting https://github.com/Lycreal/python-mirai/archive/refs/heads/fix-GroupImage.zip
  Using cached https://github.com/Lycreal/python-mirai/archive/refs/heads/fix-GroupImage.zip
Requirement already satisfied (use --upgrade to upgrade): kuriyama==0.3.6 from https://github.com/Lycreal/python-mirai/archive/refs/heads/fix-GroupImage.zip in /usr/local/python3/lib/python3.8/site-packages
Requirement already satisfied: aiohttp in /usr/local/python3/lib/python3.8/site-packages (from kuriyama==0.3.6) (3.7.4.post0)
Requirement already satisfied: pydantic in /usr/local/python3/lib/python3.8/site-packages (from kuriyama==0.3.6) (1.6.1)
Requirement already satisfied: Logbook in /usr/local/python3/lib/python3.8/site-packages (from kuriyama==0.3.6) (1.5.3)
Requirement already satisfied: async_lru in /usr/local/python3/lib/python3.8/site-packages (from kuriyama==0.3.6) (1.0.2)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/python3/lib/python3.8/site-packages (from aiohttp->kuriyama==0.3.6) (3.7.4.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/python3/lib/python3.8/site-packages (from aiohttp->kuriyama==0.3.6) (20.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/python3/lib/python3.8/site-packages (from aiohttp->kuriyama==0.3.6) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/python3/lib/python3.8/site-packages (from aiohttp->kuriyama==0.3.6) (1.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/python3/lib/python3.8/site-packages (from aiohttp->kuriyama==0.3.6) (3.0.1)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/local/python3/lib/python3.8/site-packages (from aiohttp->kuriyama==0.3.6) (4.0.0)
Requirement already satisfied: idna>=2.0 in /usr/local/python3/lib/python3.8/site-packages (from yarl<2.0,>=1.0->aiohttp->kuriyama==0.3.6) (3.1)
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

应该没错吧

**Comment by Lycreal** [comment]
添加 `--force-reinstall` 参数再试试

`pip install --force-reinstall https://github.com/Lycreal/python-mirai/archive/refs/heads/fix-GroupImage.zip`

**Comment by Soarniner** [comment]
感谢，正常了
